// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `HelloWorld.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.maycur.didi;

public interface HelloWorld extends Ice.Object,
                                    _HelloWorldOperations, _HelloWorldOperationsNC
{
    public static final String ice_staticId = "::com::maycur::didi::HelloWorld";

    public static final long serialVersionUID = 7312286149421447629L;
}
